let number = prompt('Sening isming nima?')
let user = prompt(' Sening familyang nima?')
let box = prompt('Sening yoshing nechida?')
let info = prompt('Sen qayerda yashaysan?')
let code = prompt('Senga yoqtiradigan moshina nomi?')
alert(`Mening ismim ${number} familiyam ${user} yoshim ${box} yashash joyim ${info} yoqtiradigan moshinam ${code}`)